## **Intent Classification Using Embeddings**

In [11]:
import spacy
import string


In [12]:
nlp = spacy.load("en_core_web_sm")
stop_words = nlp.Defaults.stop_words
print(stop_words)

{'whereafter', 'really', 'all', 'six', 'toward', 'n’t', 'became', 'onto', 'will', 'itself', 'might', 'ten', 'because', 'thereby', 'anywhere', 'afterwards', 'anyway', 'mostly', 'enough', 'give', 'he', 'other', 'made', 'against', 'beforehand', 'from', 'can', 'fifteen', 'of', 'through', 'sometimes', 'under', 'sometime', 'eight', 'namely', '‘s', 'anyone', 'almost', "'m", 'neither', 'your', 'but', 'otherwise', 'seem', 'nine', 'then', 'is', 'hundred', 'until', 'yourself', 'again', 'back', 'used', 'go', 'yours', 'perhaps', 'herein', 'ca', 'take', 'either', 'never', 'yet', 'once', 'have', 'part', 'together', 'wherein', 'those', 'others', 'beyond', 'now', 'quite', 'she', 'themselves', 'except', 'nothing', 'my', 'off', 'an', 'many', 'only', 'him', 'sixty', 'during', 'was', 'should', 'two', 'and', 'than', 'anything', '‘ve', 'both', 'so', 'up', 'front', 'hereupon', 'no', "'ll", '‘m', 'do', 'across', 'without', 'were', 'would', 'this', 'moreover', 'few', 'using', 'why', 'keep', 'somewhere', "'ve", 

In [13]:
punctuations = string.punctuation
print(punctuations)
     

!"#$%&'()*+,-./:;<=>?@[\]^_`{|}~


In [14]:
import spacy
import string

punctuations = string.punctuation
nlp = spacy.load("en_core_web_sm")
stop_words = nlp.Defaults.stop_words

def spacy_tokenizer(sentence):
    # Creating our token object, which is used to create documents with linguistic annotations.
    doc = nlp(sentence)



    # print(doc)
    # print(type(doc))

    # Lemmatizing each token and converting each token into lowercase
    mytokens = [ word.lemma_.lower().strip() for word in doc ]

    # print(mytokens)

    # Removing stop words
    mytokens = [ word for word in mytokens if word not in stop_words and word not in punctuations ]
    
    sentence = " ".join(mytokens)
    # return preprocessed list of tokens
    return sentence

In [15]:



s= ''''https://www.hellomagazine.com/us/ HELLO! US edition brings you the latest celebrity & royal news from the US & around the world, magazine exclusives, celeb babies, weddings, pregnancies and\xa0...https://en.wikipedia.org/wiki/Hello Hello is a salutation or greeting in the English language. It is first attested in writing from 1826. The greeting "Hello" became associated with telephones in\xa0...https://www.hello-products.com/ naturally friendly products for naturally friendly people. vegan, cruelty free, and thoughtfully formulated for everyone.https://hellogames.org/ Hello Games. Join us on our journey to create the types of games that didn\'t exist before. View Jobs. Who We Are. We are a small studio who like to harness\xa0...https://www.hellofresh.com/ Get started with America\'s Most Popular Meal Kit today! Most 5-Star Reviews ✓ The most recipe variety ✓ Fresh & affordable meal kit delivery service.https://www.facebook.com/hello/ HELLO! 2080633 likes · 48246 talking about this. The official Facebook page for HELLO! magazine & http://www.hellomagazine.com/ FOLLOW US @ https://tw.https://www.azlyrics.com/lyrics/adele/hello.html Adele "Hello": Hello, it\'s me I was wondering if after all these years you\'d like to meet To go over everything The...https://www.songfacts.com/facts/adele/hello Adele explained the song\'s meaning to i-D. "The song is about hurting someone\'s feelings but it\'s also about trying to stay in touch with myself, which\xa0...https://www.dictionary.com/browse/hello (used to express a greeting, answer a telephone, or attract attention.) (an exclamation of surprise, wonder, elation, etc.).https://helloalice.com/ Hello Alice is a free platform designed for AND by small business owners. We\'re here to guide and support you at every turn on your adventure in\xa0...https://americansongwriter.com/adele-hello-behind-the-song/ ADELE: “Hello\' actually started with the lyric, \'Hello misery.\' So you can imagine the mood I was in! [Laughs] I was f**ing miserable! But Greg Kurstin, who I\xa0...https://sandraheyersongs.com/the-story-behind-hello-by-adele/ One of Adele\'s new songs was “Hello.” The song is about a woman who is trying to reconnect with an ex-boyfriend. Is it another song about Alex?https://hellohealth.com/ Electronic Health Record, Practice Management System, Patient Portal and Telehealth solution. See how doctors can access medical technology from anywhere\xa0...https://wordpress.org/themes/hello-elementor/ Jul 5, 2023 — Hello Elementor. By Elementor. Commercial Theme. Support. This theme is free but offers additional paid commercial upgrades or support\xa0...https://twitter.com/hellomag The Duke of Sussex recognised in HELLO!\'s Kind List 2022. hellomagazine.com. The Duke of Sussex. Prince Harry supports a number of organisations.https://www.letras.com/adele/hello/ Adele - Hello (Letra y canción para escuchar) - Hello from the other side / I must\'ve called a thousand times to tell you / I\'m sorry, for everything that\xa0...https://nohello.net/en please don\'t say just hello in chat.https://www.npr.org/sections/goatsandsoda/2023/08/23/1193148718/why-a-strangers-hello-can-do-more-than-just-brighten-your-day 20 hours ago — Researchers are exploring the impact of interactions with strangers and casual acquaintances. Their findings shed light on how seemingly\xa0...https://www.gnu.org/software/hello/ GNU Hello. The GNU Hello program produces a familiar, friendly greeting. Yes, this is another implementation of the classic program that prints “Hello,\xa0...https://www.instrument.com/latest/hello-design-joins-instrument In January 2023, Los Angeles-based agency Hello Design will join Instrument, operating as an integrated client service team.https://www.britannica.com/dictionary/hello HELLO meaning: 1 : used as a greeting; 2 : the act of saying the word hello to someone as a greeting.https://www.helloneighbor.io/ We are a nonprofit organization based in Pittsburgh, Pennsylvania committed to supporting our newest neighbors, recently resettled refugee and immigrant\xa0...https://genius.com/Adele-hello-lyrics Oct 23, 2015 — Hello Lyrics: Hello, it\'s me / I was wondering if after all these years you\'d like to meet / To go over everything / They say that time\'s\xa0...https://hellobio.com/ Hello Bio, Voted Researchers Choice 2023 for highly validated, affordable reagents, supporting scientists worldwide.https://soundcloud.com/gracedaviesofficial/hello-adele Oct 26, 2015 — Stream Hello - Adele by Grace Davies on desktop and mobile. Play over 320 million tracks for free on SoundCloud.https://www.collinsdictionary.com/dictionary/english/hello hello in American English · 1. used as a greeting or response, as in telephoning · 2. used to attract attention · 3. used to express astonishment or surprise.https://www.hello.one/ HELLO Labs is a Web3 ecosystem built around producing, incubating and distributing exclusive TV shows, games, NFTs and live events.https://www.spin.com/2019/06/adele-hello-lyrics/ Jun 11, 2019 — “Hello” was the first single from Adele\'s highly-anticipated third studio album 25, which came out four years after her sophomore album, 21.https://hello-robot.com/ Provider of the Stretch Research Edition. Remarkable for its capability, portability. We\'ve reimagined the mobile manipulator.https://support.microsoft.com/en-us/windows/learn-about-windows-hello-and-set-it-up-dae28983-8242-bb2a-d3d1-87c9d265a5f0 Learn how to sign into your PC with Windows Hello using a PIN, facial recognition, or fingerprint.https://helloperiod.com/ Sustainable, award-winning and comfortable, Hello Period makes period life easier and planet-friendly. Makers of the legendary Hello Cup™ and Hello Disc™.https://www.sanrio.com/ Explore the supercute world of Sanrio, home to Hello Kitty, My Melody, Kuromi, Aggretsuko, Gudetama, and more!https://hellometeor.bandcamp.com/album/traditional-dreams-for-january Traditional Dreams For January by Hello Meteor, released 29 August 2023 1. Crescent Lanterns 2. Way Of Lakes 3. Cloud Development Timelapse 4.https://docs.github.com/en/get-started/quickstart/hello-world This tutorial teaches you GitHub essentials like repositories, branches, commits, and pull requests. You\'ll create your own Hello World repository and learn\xa0...https://podcasts.apple.com/us/podcast/hello-monday-with-jessi-hempel/id1453893304 3 days ago — Welcome to Hello Monday with Jessi Hempel – a show where LinkedIn\'s Jessi Hempel explores the changing nature of work, and how that work is\xa0...https://helloaudio.fm/ Turn your content into private podcasts that your audience can listen to on the go. Convenient consumption for them, more engagement and sales for you.https://www.helloengineer.com/ Hello Enginer is a multiplayer Hello Neighbor spin-off game where you try to escape The Golden Apple Theme Park.https://hello-tomorrow.org/ What we do · Innovation Consulting · Events · Startup competitions and acceleration programs · Thought leadership.https://hellomrmag.com/ The Hello Mr. issue archive.https://www.hellobettybethesda.com/ Hello Betty is a surf and skate inspired seafood restaurant in North Bethesda\'s Pike & Rose neighborhood.https://learnenglishkids.britishcouncil.org/listen-watch/songs/hello-hello-hello Who is B23A? Listen to a song called Hello, hello, hello and sing along. Help.https://www.cisa.gov/topics/physical-security/non-confrontational-techniques/power-hello Power of Hello ... Industries face a variety of threats, both internal and external, from hostile governments, terrorist groups, disgruntled employees and\xa0...https://helloinsight.org/ Hello Insight helps youth development organizations prove impact and improve programs, with pre-built surveys, predictive analytics, and automated reports.\'https://hellodivorce.com/ Hello Divorce makes divorce easier and more affordable. Learn about our affordable online divorce plans with as little or as much help as you need,\xa0...https://hellosundaymorning.org/ Hello Sunday Morning is an Australian not-for-profit organisation dedicated to helping people who want to change their relationship with alcohol.https://www.helloruby.com/ Welcome to the whimsical world of computing. Hello Ruby is a children\'s book and an app that teaches programming fundamentals through stories and\xa0...https://www.sandyhookpromise.org/our-programs/start-with-hello/ Our proven programs create safer and kinder schools. Start With Hello teaches empathy and empowers students to end social isolation.https://www.vocabulary.com/dictionary/hello Hello! Hi! How are you doing? Hello is a salutation or greeting commonly used to begin conversations or telephone calls. Hello has been used as an English\xa0...https://supersimple.com/song/hello/ Start off your lesson with “Hello!”, a fun and energetic song to talk about how you feel as you greet each other. Gestures & Activities. How To\xa0...https://hub.docker.com/_/hello-world hello-world. Docker Official Image. •. 1B+. •. 2.1K. Hello World! (an example of minimal Dockerization). docker pull hello-world.https://eternitymarketing.com/blog/the-surprising-history-of-hello-origins-and-evolution-of-the-greeting Mar 27, 2022 — Hello? What do you say when you answer the phone? If you\'re like most people, you say "hello." It\'s such a common, everyday word.https://hello.ef.com/ The proven way to learn a language! · A study by the University of Cambridge found it takes only 8 hours in EF Hello to master the material of a typical semester\xa0...https://hellowordl.net/ A word-guessing game.https://www.instagram.com/hellomag/?hl=en 608K Followers, 1266 Following, 10K Posts - See Instagram photos and videos from HELLO! Magazine (@hellomag)https://www.dignityhealth.org/hello-humankindness Hello humankindness starts with the proven idea that human connection leads to better health. That\'s why humankindness is at the heart of everything we do.https://adele.fandom.com/wiki/Hello_(music_video) "Hello" is a music video for Adele\'s song of the same name, taken from her third studio album, 25. It was directed and co-produced by Xavier Dolan,\xa0...https://helloworld.raspberrypi.org/ Hello World issue 21. How are you preparing young children for a digital world? This is the question this primary-teaching themed issue explores,\xa0...https://www.schools.nyc.gov/school-life/school-environment/hello NYC Public Schools Speak Your Language! Hello in English · Hello in Arabic · Hello in Bangla · Hello in Chinese · Hello in French · Hello in Albanian · Hello\xa0...https://www.hello.com/ It\'s not goodbye. It\'s see you again soon. We are pausing hello while we get ready to launch something even better. We have loved having you a part of this\xa0...https://www.letras.mus.br/adele/hello/ Adele - Hello (Letra e música para ouvir) - Hello from the other side / I must\'ve called a thousand times to tell you / I\'m sorry, for everything that I\'ve\xa0...https://www.merriam-webster.com/dictionary/hello The meaning of HELLO is an expression or gesture of greeting —used interjectionally in greeting, in answering the telephone, or to express surprise.https://open.spotify.com/track/62PaSfnXSMyLshYJrlTuL3 Hello. Adele. 2520154:55.https://en.wiktionary.org/wiki/hello hello. Language; Watch · Edit. See also: helló. Contents. 1 English. 1.1 Alternative forms; 1.2 Etymology; 1.3 Pronunciation; 1.4 Interjection.https://dictionary.cambridge.org/us/dictionary/english/hello Meaning of hello in English ... used when meeting or greeting someone: Hello, Paul. I haven\'t seen you for ages. I know her vaguely - we\'ve exchanged hellos a few\xa0...https://www.etymonline.com/word/hello greeting between persons meeting, 1848, the early references are to the U.S. western frontier (where hello, the house was said to be the usual greeting upon\xa0...https://en.wikipedia.org/wiki/Hello_(Adele_song) "Hello" is a song recorded by English singer-songwriter Adele, released on 23 October 2015 by XL Recordings as the lead single from her third studio album,\xa0...https://elementor.com/products/hello-theme/ 100%Tailored to Elementor. Hello works in pure harmony with Elementor\'s popular page builder and minimizes the need for other plugins.https://www.hello-dmc.com/ WHERE WE ARE · SOUTH FLORIDA · LAS VEGAS · NASHVILLE · NEW YORK · CENTRAL / TEXAS · NORTH / TEXAS · WASHINGTON, D.C. · Hello! USA.https://www.thesaurus.com/browse/hello Find 20 ways to say HELLO, along with antonyms, related words, and example sentences at Thesaurus.com, the world\'s most trusted free thesaurus.https://www.helloheart.com/ Hello Heart\'s digital coaching app helps people manage heart health, and drives high employee engagement while potentially reducing medical claims costs.https://www.nomanssky.com/ Entire galaxies lie waiting to be discovered. Story. Experience infinite freedom, or uncover the secrets of the universe with more than 30 hours of story.https://www.hellopizza.com/ Hello Pizza is chef Ann Kim\'s New York style pizzeria offering pizza, salads and meatball subs for dining in, take out and delivery.https://www.hellolucky.com/ Hello!Lucky is all about using creativity to spread joy, fun, and kindness. Founded by sisters Eunice and Sabrina Moyle in 2003, Hello!https://www.hellosailornc.com/ A bright and sunny waterfront restaurant and bar, open all day. Best restaurant in Lake Norman, best view of the water. 704-997-5365.https://www.hellobar.com/ Types of Popups Included With All Hello Bar Plans. Bars. Persistent header and footer bars that scroll with your visitors. Modals. Popups that\xa0...https://www.helloapparelstore.com/ Hello Apparel, I\'m So Tired, I\'m Not Tired, I\'m So Pregnant, T-Shirts, Sweatshirts, Leggings, One-Piece, Accessories & More! Matching Sets for the Whole\xa0...https://store.steampowered.com/app/1856190/Hello_Engineer_Scrap_Machines_Constructor/ Hello Engineer is a multiplayer machinary-construction game set in the Hello Neighbor universe for up to 4 players! Scavenge, craft and overcome challenges\xa0...https://www.hellofax.com/ Ditch your fax machine! HelloFax makes it easy for you to fax online right from your computer. Keep your current number or get a new one. Try us free!https://hellobello.com/ Because parents shouldn\'t have to choose between what\'s best for their baby, their budget, and the planet.https://www.imdb.com/title/tt5431624/ Adele: Hello: Directed by Xavier Dolan. With Adele, Tristan Mack Wilds. With a new song and a brand new music video Adele shows betrayal, regret and sorrow.https://commonpractice.com/products/hello-game Hello is a conversation game. It\'s the easy, non-threatening way to start a conversation with your family and friends about what matters most to you.https://hello-sunshine.com/ Reese Witherspoon - Candle - HelloSunshine.https://www.hellomerch.com/ Started in 2008 as an outlet for bands, musicians, creative artists and businesses to manufacture and sell merchandise anywhere, without giving up their rights.https://www.hellomonday.com/ Hello Monday is a creative studio in New York, Copenhagen, and Aarhus that handcrafts digital (and magical) products, brands, and experiences.https://shop.highlights.com/hello-magazines-subscription Hello magazine is filled with colorful images, whimsical read-aloud stories and simple activities. Delight little ones ages 0-2 with a Highlights Hello\xa0...https://hellotractor.com/ Use Hello Tractor detailed reporting to access innovative pay-as-you-go financing to grow your own fleet. Access Equipment Financing.https://www.bbc.com/news/uk-england-london-66591708 1 day ago — A pilot in Hammersmith saw stickers put on some buses to encourage people to say hello or thank you to the driver. In non-stickered buses,\xa0...https://www.hellobettyoceanside.com/ Hello Betty is a surf and skate inspired seafood restaurant near the beach in Oceanside, CA.https://www.hellorobincookies.com/ Hello Robin: Sharing Cookies and Kindness since 2013.https://www.hellosign.com/ Dropbox Sign (formerly HelloSign) is the easiest way to send, receive and manage legally binding electronic signatures. Try it free!https://www.hellobistro.com/ Salads. Burgers. Together. Two delicious eats unified under one roof.'
'''
spacy_tokenizer(s)

"https://www.hellomagazine.com/us/ hello edition bring late celebrity royal news world magazine exclusive celeb baby wedding pregnancy ... https://en.wikipedia.org/wiki/hello hello salutation greeting english language attest write 1826 greeting hello associate telephone ... https://www.hello-products.com/ naturally friendly product naturally friendly people vegan cruelty free thoughtfully formulate everyone.https://hellogames.org/ hello games join journey create type game exist view jobs small studio like harness ... https://www.hellofresh.com/ start america popular meal kit today 5 star reviews ✓ recipe variety ✓ fresh affordable meal kit delivery service.https://www.facebook.com/hello/ hello 2080633 like · 48246 talk official facebook page hello magazine http://www.hellomagazine.com/ follow https://tw.https://www.azlyrics.com lyric adele hello.html adele hello hello wonder year like meet the...https://www.songfacts.com/facts/adele/hello adele explain song meaning d. song hurt feeling

In [16]:
from main import *

In [17]:
keywords_new= [
    'red dot on beats headphones', 
    'red light on beats headphones', 
    'why are my beats red', 
    'best wireless headphones for vinyl', 
    'best wireless headphones for listening to vinyl', 
    'best wireless headphones for turntable'
]

In [18]:
# embedings1= []
# for i in keywords_new:
#     s_i= (generate_keyword_summary(i))
#     e_i= generate_large_embeddings(s_i)
#     embedings1.append(e_i)
    
# len(embedings1)

In [19]:
# embedings2= embedings1

In [20]:
# generate_cosine_similarity(embedings1, embedings2)

In [21]:
import pandas as pd

In [22]:
# import os
# os.chdir('..')
# %pwd

In [25]:
df= pd.read_csv('data/warewe_clustering_intent.csv')
df.head()

Keyword  Search volume                       Cluster  \
0  beats headphones at best buy           3600  beats headphones at best buy   
1     best buy beats headphones           3600  beats headphones at best buy   
2    best buy: beats headphones           3600  beats headphones at best buy   
3     best buy headphones beats           3600  beats headphones at best buy   
4     beats headphones best buy           3600  beats headphones at best buy   

                      Topical cluster                         Spoke  Article  \
0  which is the best beats headphones  beats headphones at best buy        0   
1  which is the best beats headphones  beats headphones at best buy        0   
2  which is the best beats headphones  beats headphones at best buy        0   
3  which is the best beats headphones  beats headphones at best buy        0   
4  which is the best beats headphones  beats headphones at best buy        0   

   Product/Category  Other page type Dominant Intent  
0                10                0   Transactional  
1                10                0   Transactional  
2                10                0   Transactional  
3                10                0   Transactional  
4                10                0   Transactional

In [26]:
df['Dominant Intent'].value_counts()

Dominant Intent
Transactional    4156
Informational     832
Other              12
Name: count, dtype: int64

In [1]:
intents= {
    'informational': '''Informational intent is when users are seeking information, answers, or explanations. They want to learn about a specific topic, understand a concept, or find facts. These searches often begin with question words like "what," "how," "why," or "who." Example: "What is photosynthesis?" Goal: The user wants to understand the process of photosynthesis and gain knowledge about it.''',
    
    'navigational':'''Informational intent is when users are seeking information, answers, or explanations. They want to learn about a specific topic, understand a concept, or find facts. These searches often begin with question words like "what," "how," "why," or "who." Example: "What is photosynthesis?" Goal: The user wants to understand the process of photosynthesis and gain knowledge about it.''',
    
    'transactional': '''Transactional intent is driven by users who intend to perform a specific action, such as making a purchase, signing up for a service, or downloading something.Example: "Buy iPhone 12 online"Goal: The user intends to make a purchase of an iPhone 12 online.''',
    
    'commercial': '''Commercial investigational intent is when users are in the research phase of a potential purchase. They are comparing products, reading reviews, and seeking information before making a decision.Example: "Best laptop for graphic design"Goal: The user is looking for information about laptops suitable for graphic design work, with the intention of purchasing one.''',
    
    'local': '''Local intent is when users are searching for products, services, or information specific to a particular location. These searches often include phrases like city names or "near me." Example: "Restaurants near me" Goal: The user wants to find nearby restaurants for dining out.'''
}



In [19]:
reverse_intent= {
    0: 'informational',
    1: 'navigational',
    2: 'transactional',
    3: 'commercial',
    4: 'local'
}

In [2]:
from main import *

/home/ubuntu/embedding/venv/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
No sentence-transformers model found with name /home/ubuntu/.cache/torch/sentence_transformers/efederici_e5-large-v2-4096. Creating a new one with MEAN pooling.


In [5]:
intent_embeddings= []
for i in intents:
    e_i= generate_base_embeddings(intents[i])
    intent_embeddings.append(e_i)

In [7]:
keywords_new= [
    'beats headphones at best buy',
    'best buy beats headphones',
    'best buy: beats headphones',
    'best buy headphones beats',
    'beats headphones best buy',
    'beats best buy headphones',
    'which is the best beats headphones'

]



In [18]:
# from basic_cleaner import clean
keywords_embedding= []
for i in keywords_new:
    s_i= generate_keyword_summary(i)
    e_i= generate_base_embeddings(s_i)
    keywords_embedding.append(e_i)
    # print(generate_cosine_similarity(intent_embeddings, [e_i]))
    

In [20]:
len(keywords_embedding)

7

In [32]:
for i in keywords_embedding:


    cos_similarity= generate_cosine_similarity(intent_embeddings, i)
    dominant_intent= reverse_intent[int(np.argmax(cos_similarity))]
    print(f'dominant_intent= {dominant_intent}')
    print(cos_similarity, '\n\n')

dominant_intent= commercial
tensor([[0.7161],
        [0.7161],
        [0.7531],
        [0.7600],
        [0.7371]]) 


dominant_intent= commercial
tensor([[0.7297],
        [0.7297],
        [0.7547],
        [0.7648],
        [0.7401]]) 


dominant_intent= commercial
tensor([[0.6916],
        [0.6916],
        [0.7296],
        [0.7321],
        [0.7119]]) 


dominant_intent= commercial
tensor([[0.7069],
        [0.7069],
        [0.7439],
        [0.7484],
        [0.7301]]) 


dominant_intent= commercial
tensor([[0.7024],
        [0.7024],
        [0.7326],
        [0.7396],
        [0.7095]]) 


dominant_intent= commercial
tensor([[0.7062],
        [0.7062],
        [0.7410],
        [0.7431],
        [0.7260]]) 


dominant_intent= transactional
tensor([[0.6769],
        [0.6769],
        [0.7247],
        [0.7215],
        [0.7087]]) 




In [40]:
transactional= sum(keywords_embedding)/len(keywords_embedding)

In [41]:
transactional.shape

(768,)

In [42]:
intent_embeddings[2]= transactional

In [43]:
for i in keywords_embedding:


    cos_similarity= generate_cosine_similarity(intent_embeddings, i)
    dominant_intent= reverse_intent[int(np.argmax(cos_similarity))]
    print(f'dominant_intent= {dominant_intent}')
    print(cos_similarity, '\n\n')

dominant_intent= transactional
tensor([[0.7161],
        [0.7161],
        [0.9806],
        [0.7600],
        [0.7371]]) 


dominant_intent= transactional
tensor([[0.7297],
        [0.7297],
        [0.9800],
        [0.7648],
        [0.7401]]) 


dominant_intent= transactional
tensor([[0.6916],
        [0.6916],
        [0.9784],
        [0.7321],
        [0.7119]]) 


dominant_intent= transactional
tensor([[0.7069],
        [0.7069],
        [0.9812],
        [0.7484],
        [0.7301]]) 


dominant_intent= transactional
tensor([[0.7024],
        [0.7024],
        [0.9753],
        [0.7396],
        [0.7095]]) 


dominant_intent= transactional
tensor([[0.7062],
        [0.7062],
        [0.9869],
        [0.7431],
        [0.7260]]) 


dominant_intent= transactional
tensor([[0.6769],
        [0.6769],
        [0.9385],
        [0.7215],
        [0.7087]]) 




In [46]:
s_i= generate_keyword_summary("buy iphone 13")
e_i= generate_base_embeddings(s_i)

cos_similarity= generate_cosine_similarity(intent_embeddings, e_i)
dominant_intent= reverse_intent[int(np.argmax(cos_similarity))]
print(f'dominant_intent= {dominant_intent}')
print(cos_similarity, '\n\n')

dominant_intent= transactional
tensor([[0.7120],
        [0.7120],
        [0.8408],
        [0.7352],
        [0.7128]]) 


