In [ ]:
data= d['data']
data.keys()

In [ ]:
# data= d['data']
results= data['results']
results

In [ ]:
s= ""

for i in results:
    s+=i['url']+' '
    s+=i['description']

In [ ]:
s

In [ ]:
s= s.replace("https://", '')
s= s.replace("/", '')
s= s.replace(",", '')
s= s.replace("www.", '')

In [ ]:
from summa import summarizer
s=summarizer.summarize(s, words=200).replace('\n', ' ')

In [ ]:
with open("x.txt", "w") as f:
    f.write(s)

In [85]:
import requests


In [92]:
response= requests.api.get('https://2qq35q1je7.execute-api.us-east-1.amazonaws.com/?search=hello')

In [93]:
d= json.loads(response.text)

In [ ]:
d

In [ ]:
d['data']

In [96]:
data= d['data']
results= data['results']

In [97]:
s= ""

for i in results:
    s+=i['url']+' '
    s+=i['description']
    
s

'https://www.hellomagazine.com/us/ HELLO! US edition brings you the latest celebrity & royal news from the US & around the world, magazine exclusives, celeb babies, weddings, pregnancies and\xa0...https://en.wikipedia.org/wiki/Hello Hello is a salutation or greeting in the English language. It is first attested in writing from 1826. The greeting "Hello" became associated with telephones in\xa0...https://www.hello-products.com/ naturally friendly products for naturally friendly people. vegan, cruelty free, and thoughtfully formulated for everyone.https://www.facebook.com/hello/ HELLO! 2080655 likes · 48246 talking about this. The official Facebook page for HELLO! magazine & http://www.hellomagazine.com/ FOLLOW US @ https://tw.https://www.hellofresh.com/ Get started with America\'s Most Popular Meal Kit today! Most 5-Star Reviews ✓ The most recipe variety ✓ Fresh & affordable meal kit delivery service.https://hellogames.org/ Hello Games. Join us on our journey to create the types of game

# Keywords_Similarity

In [154]:
import json
from summa import summarizer
import time

def generate_keyword_summary(keyword):
    """Generate a summary of the keyword"""
    response= requests.api.get(f'https://2qq35q1je7.execute-api.us-east-1.amazonaws.com/?search={keyword}')
    d= json.loads(response.text)
    
    data= d['data']
    results= data['results']
    
    s= ""
    

    for i in results:
        s+=i['url']+' '
        s+=i['description']
        
    s= s.replace("https://", '')
    s= s.replace("/", '')
    s= s.replace(",", ' ')
    s= s.replace("www.", '')
        
    summary=summarizer.summarize(s, words=250).replace('\n', ' ')
    
    return summary

In [108]:
keywords= [
    'beats headphones at best buy',
    'best cat ear headphones',
    'best buy beats headphones',
    'best buy: beats headphones',
    'best buy headphones beats',
    'beats headphones best buy',
    'beats best buy headphones',
    'which is the best beats headphones',
    'which beats headphones are the best',
    'best beats headphones',
    'which beats headphones are best',
    'beats headphones compared',
    'compare beats headphones',
    'beats best headphones',
    'which beats headphones is the best',
    'best headphones beats',
    'recording studio headphones',
    'headphones for recording',
    'studio recording headphones',
    'best musicians headphones',
    'beats latest headphones',
    'color beats headphones',
    'beats headphones latest',
    'latest beats headphones',
    'newest beats headphones'

]

In [100]:
from main import *

### GTE BASE

In [101]:
print(keywords[0])
s1= generate_keyword_summary(keywords[0])
e1= generate_base_embeddings(s1)
e1.shape

beats headphones at best buy


(768,)

In [102]:
for i in keywords:
    print(i)
    s_i= (generate_keyword_summary(i))
    e_i= generate_base_embeddings(s_i)
    print(generate_cosine_similarity(e1, e_i))
    time.sleep(30)

beats headphones at best buy
tensor([[0.9324]])
best buy beats headphones
tensor([[0.9271]])
best buy: beats headphones
tensor([[0.9444]])
best buy headphones beats
tensor([[0.9849]])
beats headphones best buy
tensor([[0.9407]])
beats best buy headphones
tensor([[0.9317]])
which is the best beats headphones
tensor([[0.9207]])
which beats headphones are the best
tensor([[0.9263]])
best beats headphones
tensor([[0.9198]])
which beats headphones are best
tensor([[0.9068]])
beats headphones compared
tensor([[0.8985]])
compare beats headphones
tensor([[0.9092]])
beats best headphones
tensor([[0.8996]])
which beats headphones is the best
tensor([[0.8959]])
best headphones beats
tensor([[0.8987]])
recording studio headphones
tensor([[0.8660]])
headphones for recording
tensor([[0.8614]])
studio recording headphones
tensor([[0.8595]])
best musicians headphones
tensor([[0.8598]])
beats latest headphones
tensor([[0.9114]])
color beats headphones
tensor([[0.9217]])
beats headphones latest
tensor([

### GTE Large

In [125]:
print(keywords[0])
# s1= generate_keyword_summary(keywords[0])
s1= generate_keyword_summary("best beats headphones india")
e1= generate_large_embeddings(s1)
e1.shape

beats headphones at best buy


(1024,)

In [126]:
print(keywords[0])
# s2= generate_keyword_summary(keywords[1])
s2= generate_keyword_summary('best beats headphones united kingdom')
e2= generate_large_embeddings(s2)
e2.shape

beats headphones at best buy


(1024,)

In [127]:
s2

"Best cheap true wireless earbuds · Bose QuietComfort Earbuds II\xa0...pricerunner.comspbeats-by-dre-headphones.html 1000+ products · Beats Solo3 Wireless · Beats Studio Buds · Beats Fit Pro · Beats Powerbeats Pro · Beats Studio3 Wireless · Beats Flex · Beats Urbeats 2.0 · Beats\xa0...wired.comgallerybest-wireless-headphones Feb 13 2023 — The Beats Fit Pro (910 WIRED Recommends) are also one of our favorite wireless earbuds right now thanks to their excellent integration with\xa0...jabra.com Headsets for office & call center with noise cancellation and superior sound - Bluetooth headsets and speakers - Wireless sport headphones - True wireless\xa0...techadvisor.comarticle723714best-kids-headphones.html Aug 14 2023 — iClever TransNova BTH16 – Best value kids wireless headphones ... · Biggest Technology\xa0...playstation.comen-gbaccessoriespulse-3d-wireless-headset Discover how good PS5 games can sound with the official PULSE 3D wireless headset fine-tuned for 3D audio with PlayStation 5

In [128]:
s1

"✓Best Deals ✓Fast Shipping ✓Latest\xa0...amazon.inHeadphones-Beats-Earbuds-Accessoriess?rh=n%3A1388921031%2Cp_89%3ABeats Beats Studio Buds – True Wireless Noise Cancelling Earphones – Active Noise Cancelling IPX4 Rating Compatible with Apple & Android Class 1 Bluetooth\xa0...cnn.comcnn-underscoredreviewsbest-beats-headphones Aug 10 2023 — Here are the best Beats headphones we've tested from the classic Beats Solo 3 to the stylish and compact Beats Fit Pro.smartprix.commobile_headphonesbeats-brand This list contains 28 Beats Headphones And Earphones in India. Apple W1 chip.cnet.comtechmobilebest-wireless-headphones Jul 24 2023 — Best wireless headphones of 2023 · Sony WH-1000XM5 · Apple AirPods Pro 2 · Sennheiser Momentum 4 Wireless · Sony CH-720N · Apple AirPods Max · 1More\xa0...apple.comshopaccessoriesallbeats Beats by Dr. Dre · Beats Studio Pro Wireless Headphones — Sandstone · Beats Studio Buds + True Wireless Noise Cancelling Earbuds — Transparent · Beats Fit Pro —\xa0...pricedek

In [129]:
util.cos_sim(e1, e2)

tensor([[0.9399]])

In [131]:
keywords_new= [
    'red dot on beats headphones', 
    'red light on beats headphones', 
    'why are my beats red', 
    'best wireless headphones for vinyl', 
    'best wireless headphones for listening to vinyl', 
    'best wireless headphones for turntable'
]

In [132]:
embedings1= []
for i in keywords_new:
    s_i= (generate_keyword_summary(i))
    e_i= generate_large_embeddings(s_i)
    embedings1.append(e_i)
    
len(embedings1)

6

In [133]:
embedings2= embedings1

In [134]:
generate_cosine_similarity(embedings1, embedings2)

/home/ubuntu/embedding/venv/lib/python3.10/site-packages/sentence_transformers/util.py:36: UserWarning: Creating a tensor from a list of numpy.ndarrays is extremely slow. Please consider converting the list to a single numpy.ndarray with numpy.array() before converting to a tensor. (Triggered internally at ../torch/csrc/utils/tensor_new.cpp:245.)
  a = torch.tensor(a)


tensor([[1.0000, 0.9613, 0.9505, 0.7789, 0.8108, 0.8075],
        [0.9613, 1.0000, 0.9556, 0.7863, 0.8131, 0.8121],
        [0.9505, 0.9556, 1.0000, 0.7961, 0.8203, 0.8224],
        [0.7789, 0.7863, 0.7961, 1.0000, 0.9381, 0.9430],
        [0.8108, 0.8131, 0.8203, 0.9381, 1.0000, 0.9544],
        [0.8075, 0.8121, 0.8224, 0.9430, 0.9544, 1.0000]])

In [159]:
embedings1= []
for i in keywords_new:
    s_i= (generate_keyword_summary(i))
    e_i= generate_large_embeddings(s_i)
    embedings1.append(e_i)
    
len(embedings1)

6

In [160]:
embedings2= embedings1

In [161]:
generate_cosine_similarity(embedings1, embedings2)

tensor([[1.0000, 0.9521, 0.9696, 0.8054, 0.7913, 0.8085],
        [0.9521, 1.0000, 0.9649, 0.8351, 0.8208, 0.8379],
        [0.9696, 0.9649, 1.0000, 0.8135, 0.7913, 0.8219],
        [0.8054, 0.8351, 0.8135, 1.0000, 0.9266, 0.9765],
        [0.7913, 0.8208, 0.7913, 0.9266, 1.0000, 0.9166],
        [0.8085, 0.8379, 0.8219, 0.9765, 0.9166, 1.0000]])

In [162]:
with open('x.txt', 'w') as f:

    f.write(generate_keyword_summary(keywords_new[-1]))

In [163]:
with open('y.txt', 'w') as f:

    f.write(generate_keyword_summary(keywords_new[-2]))

In [164]:
# !pip install summa-visualization

In [169]:
# generate_base_embeddings("Hell0 "*400)

In [167]:
generate_bge_large_embeddings("Hell0 "*400) 

array([-0.1466239 , -0.32929528,  0.10449558, ...,  0.2036759 ,
       -0.69713056,  0.18842849], dtype=float32)

In [165]:
embedings2= []
for i in keywords_new:
    s_i= (generate_keyword_summary(i))
    e_i= generate_large_embeddings(s_i)
    embedings2.append(e_i)
    
len(embedings2)

6

In [166]:
generate_cosine_similarity(embedings1, embedings2)

tensor([[0.9935, 0.9521, 0.9623, 0.7833, 0.8211, 0.8074],
        [0.9482, 1.0000, 0.9638, 0.8148, 0.8472, 0.8445],
        [0.9701, 0.9649, 0.9894, 0.7889, 0.8255, 0.8166],
        [0.7962, 0.8351, 0.8028, 0.9446, 0.9159, 0.9179],
        [0.7798, 0.8208, 0.7862, 0.9441, 0.9204, 0.9165],
        [0.8003, 0.8379, 0.8086, 0.9284, 0.9233, 0.9248]])

In [106]:
for i in keywords:
    print(i)
    s_i= (generate_keyword_summary(i))
    e_i= generate_large_embeddings(s_i)
    print(generate_cosine_similarity(e1, e_i))
    print()
    time.sleep(30)

beats headphones at best buy


tensor([[0.9826]])

best buy beats headphones
tensor([[0.9652]])

best buy: beats headphones
tensor([[0.9703]])

best buy headphones beats
tensor([[0.9503]])

beats headphones best buy
tensor([[0.9529]])

beats best buy headphones
tensor([[0.9694]])

which is the best beats headphones
tensor([[0.9276]])

which beats headphones are the best
tensor([[0.9136]])

best beats headphones
tensor([[0.9360]])

which beats headphones are best
tensor([[0.9238]])

beats headphones compared
tensor([[0.9228]])

compare beats headphones
tensor([[0.9322]])

beats best headphones
tensor([[0.9081]])

which beats headphones is the best
tensor([[0.9389]])

best headphones beats
tensor([[0.9029]])

recording studio headphones
tensor([[0.8580]])

headphones for recording
tensor([[0.8534]])

studio recording headphones
tensor([[0.8568]])

best musicians headphones
tensor([[0.8688]])

beats latest headphones


KeyError: 'data'

### BGE Large

In [141]:
print(keywords[0])
s1= generate_keyword_summary(keywords[0])
e1= generate_bge_large_embeddings(s1)
e1.shape

beats headphones at best buy


(1024,)

In [142]:
from random import randint
embeddings_matrix1= []
for i in keywords:
    print(i)
    t= randint(1, 20)
    s_i= (generate_keyword_summary(i))
    e_i= generate_bge_large_embeddings(s_i)
    print(generate_cosine_similarity(e1, e_i))
    embeddings_matrix1.append(e_i)
    print()
    time.sleep(t)

beats headphones at best buy
tensor([[0.9491]])

best cat ear headphones
tensor([[0.8473]])

best buy beats headphones
tensor([[0.9558]])

best buy: beats headphones
tensor([[0.9530]])

best buy headphones beats
tensor([[0.9779]])

beats headphones best buy
tensor([[0.9552]])

beats best buy headphones
tensor([[0.9524]])

which is the best beats headphones
tensor([[0.9376]])

which beats headphones are the best
tensor([[0.9349]])

best beats headphones


KeyError: 'data'

In [ ]:
embeddings_matrix2= embeddings_matrix1

NameError: name 'embeddings_matrix1' is not defined